name: Test

on:
  workflow_call:
    inputs:
      my-input:
        description: Input
    secrets:
      my-secret:
        description: Token

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.my-input }}
      - run: echo ${{ secrets.my-secret }}
