name: Test

on:
  workflow_call:
    secrets:
      my-secret:
        description: Token

jobs:
  job:
    runs-on: ubuntu-latest
    env:
      secret: ${{ secrets.my-secret }}
    steps:
      - run: echo "${secret}" | base64
