name: Test

on:
  workflow_call:
    secrets:
      TOKEN:
        description: Token
        required: false

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.TOKEN }}
